################################################################################
#
# Host Setup Section
# ESXIhosts role configuration is applied to all hosts
#
################################################################################
---
#- hosts: localhost
- hosts: esxi
  gather_facts: no
  serial: 1
  vars_files:
    - group_vars/secrets.yml
    - group_vars/vmware.yml
  roles:
    - role: VMware/ESXIhosts
